### ISSUE TITLE
Walking animation is playing running footsteps audio

### ISSUE THREAD

**Issue by nigelmerle** [michaelday008/AnyRPGCore#73] opened 2021-12-23 10:00 UTC
Walking animation is playing running footsteps audio

**Comment by nigelmerle** [comment] 2021-12-24 04:50
Walking animation is playing running footsteps audio instead

**Comment by michaelday008** [comment] 2021-12-24 06:14
This is expected.  There is currently no way to get a different sound for walking vs running if you are using the loop.

If you would prefer to have the footstep sound play at the exact moment the foot touches the ground, you can adjust the settings on the unit profile to play on footstep, and use the footstep hits audio profile instead of the loop.

Closing this ticket since this is not a bug.

![image](https://user-images.githubusercontent.com/49324924/147323733-f7f76ab4-4ea6-4030-97f5-f22b1e04fe03.png)

**Closed by michaelday008** 2021-12-24 06:14 UTC
